CREATE TABLE "ADMIN"."SYS_USER_ROLE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "UID" INT NULL,
 "RID" INT NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "ADMIN"."SYS_USER"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "USERNAME" VARCHAR(20) NULL,
 "PASSWORD" VARCHAR(20) NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "ADMIN"."SYS_ROLE_MENU"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "RID" INT NULL,
 "MID" INT NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "ADMIN"."SYS_ROLE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "ROLE_NAME" VARCHAR(20) NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "ADMIN"."SYS_MENU"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "PARENT_ID" INT NULL,
 "TITLE" VARCHAR(50) NULL,
 "HREF" VARCHAR(200) NULL,
 "PERMISSION" VARCHAR(200) NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

SET IDENTITY_INSERT "ADMIN"."SYS_MENU" ON;
INSERT INTO "ADMIN"."SYS_MENU"("ID","PARENT_ID","TITLE","HREF","PERMISSION") VALUES(1,0,'权限管理',null,null);
INSERT INTO "ADMIN"."SYS_MENU"("ID","PARENT_ID","TITLE","HREF","PERMISSION") VALUES(2,1,'用户管理',null,'sys:user:list');
INSERT INTO "ADMIN"."SYS_MENU"("ID","PARENT_ID","TITLE","HREF","PERMISSION") VALUES(3,1,'角色管理',null,'sys:role:list');
INSERT INTO "ADMIN"."SYS_MENU"("ID","PARENT_ID","TITLE","HREF","PERMISSION") VALUES(4,1,'菜单管理',null,'sys:menu:list');
INSERT INTO "ADMIN"."SYS_MENU"("ID","PARENT_ID","TITLE","HREF","PERMISSION") VALUES(5,0,'川菜',null,null);
INSERT INTO "ADMIN"."SYS_MENU"("ID","PARENT_ID","TITLE","HREF","PERMISSION") VALUES(6,5,'东坡肘子',null,null);
INSERT INTO "ADMIN"."SYS_MENU"("ID","PARENT_ID","TITLE","HREF","PERMISSION") VALUES(7,5,'冷锅鱼',null,null);
INSERT INTO "ADMIN"."SYS_MENU"("ID","PARENT_ID","TITLE","HREF","PERMISSION") VALUES(8,5,'石磨豆花',null,null);

SET IDENTITY_INSERT "ADMIN"."SYS_MENU" OFF;
SET IDENTITY_INSERT "ADMIN"."SYS_ROLE" ON;
INSERT INTO "ADMIN"."SYS_ROLE"("ID","ROLE_NAME") VALUES(1,'admin');

SET IDENTITY_INSERT "ADMIN"."SYS_ROLE" OFF;
SET IDENTITY_INSERT "ADMIN"."SYS_ROLE_MENU" ON;
INSERT INTO "ADMIN"."SYS_ROLE_MENU"("ID","RID","MID") VALUES(1,1,1);
INSERT INTO "ADMIN"."SYS_ROLE_MENU"("ID","RID","MID") VALUES(2,1,2);
INSERT INTO "ADMIN"."SYS_ROLE_MENU"("ID","RID","MID") VALUES(3,1,3);
INSERT INTO "ADMIN"."SYS_ROLE_MENU"("ID","RID","MID") VALUES(4,1,4);
INSERT INTO "ADMIN"."SYS_ROLE_MENU"("ID","RID","MID") VALUES(5,1,5);
INSERT INTO "ADMIN"."SYS_ROLE_MENU"("ID","RID","MID") VALUES(6,1,6);
INSERT INTO "ADMIN"."SYS_ROLE_MENU"("ID","RID","MID") VALUES(7,1,7);
INSERT INTO "ADMIN"."SYS_ROLE_MENU"("ID","RID","MID") VALUES(8,1,8);

SET IDENTITY_INSERT "ADMIN"."SYS_ROLE_MENU" OFF;
SET IDENTITY_INSERT "ADMIN"."SYS_USER" ON;
INSERT INTO "ADMIN"."SYS_USER"("ID","USERNAME","PASSWORD") VALUES(1,'xpp','123');

SET IDENTITY_INSERT "ADMIN"."SYS_USER" OFF;
SET IDENTITY_INSERT "ADMIN"."SYS_USER_ROLE" ON;
INSERT INTO "ADMIN"."SYS_USER_ROLE"("ID","UID","RID") VALUES(1,1,1);

SET IDENTITY_INSERT "ADMIN"."SYS_USER_ROLE" OFF;
ALTER TABLE "ADMIN"."SYS_USER_ROLE" ADD CONSTRAINT  CLUSTER  PRIMARY KEY("ID") ENABLE ;

ALTER TABLE "ADMIN"."SYS_USER" ADD CONSTRAINT  CLUSTER  PRIMARY KEY("ID") ENABLE ;

ALTER TABLE "ADMIN"."SYS_ROLE_MENU" ADD CONSTRAINT  CLUSTER  PRIMARY KEY("ID") ENABLE ;

ALTER TABLE "ADMIN"."SYS_ROLE" ADD CONSTRAINT  CLUSTER  PRIMARY KEY("ID") ENABLE ;

ALTER TABLE "ADMIN"."SYS_MENU" ADD CONSTRAINT  CLUSTER  PRIMARY KEY("ID") ENABLE ;

